### ISSUE TITLE
Options to enable only certain features on `parse`

### ISSUE THREAD

**Issue by blakeembrey** [rlidwka/jju#17]
For example, I need to support comments, but I would prefer not to support the unquoted keys. Basically, the mode is `json+comments`.

**Comment by rlidwka** [comment]
I don't think it's good idea to restrict one feature of json5, but not another. If people want to use unquoted keys, why not just let them?

However, `json+comments` is a very popular format, so I was thinking about supporting it anyway. Please, take a look at #19, is this implementations good enough for your use-cases?

**Comment by blakeembrey** [comment]
Awesome, cheers! That looks great.

I don't want people using unquoted keys because I'm using this as a parser for a different project and don't want to support things that won't work in the original project. E.g. the TypeScript compiler parser with comments.

**Comment by rlidwka** [comment]
changes published as `jju@1.3.0`
